// Basic authentication
###
GET http://localhost:3007/home/ HTTP/1.1
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbGEgbmFnZW5kcmEga3VtYXIiLCJpYXQiOjE2NjU4ODA3ODN9.-QzvEf_dSI-iD-ZqKj_JevbB7vrt8VVzGvnC04PBwBk
Content-Type: application/json

###
GET http://localhost:3007/profile/ HTTP/1.1
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbGEgbmFnZW5kcmEga3VtYXIiLCJpYXQiOjE2NjU4ODA3ODN9.-QzvEf_dSI-iD-ZqKj_JevbB7vrt8VVzGvnC04PBwBk
Content-Type: application/json


###
GET http://localhost:3001/ HTTP/1.1
Content-Type: application/json

// The request body is provided in place
###
POST http://localhost:3001/signup/ HTTP/1.1
Content-Type: application/json

{ 
    "name" : "bala nagendra kumar", 
    "email": "balutarock71117@gmail.com",
    "password":"nagendra7@"
}

###
POST http://localhost:3001/login/ HTTP/1.1
Content-Type: application/json

{
    "name" : "bala nagendra kumar",
    "password":"nagendra7@"
}


###
GET http://localhost:3001/v1/results/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/v1/result/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/v1/result-post HTTP/1.1
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbGEgbmFnZW5kcmEga3VtYXIiLCJpYXQiOjE2NzczNTQ2OTR9.GbP8Gwd4LNZFnTxog40ilXJnZqCojL-IpRicxtx2TLc
Content-Type: application/json

{
    "firstPrice" : {"amount":"10,00,000","ticket_number":"1234567890"},
    "secondPrice": {"amount":"5,00,000","ticket_number":"1234567890"},
    "thirdPrice":{"amount":"1,20,000","ticket_number":"1234567890"},
    "fouthPrice":{"amount":"50,000","ticket_number":"1234567890"},
    "fifthPrice":{"amount":"20,000","ticket_number":"1234567890"},
    "sixthPrice":{"amount":"15,000","ticket_number":"1234567890"},
    "seventhPrice":{"amount":"6,000","ticket_number":"1234567890"},
    "eightPrice":{"amount":"6,000","ticket_number":"1234567890"},
    "ninthPrice":{"amount":"5,000","ticket_number":"1234567890"},
    "tenthPrice":{"amount":"5,000","ticket_number":"1234567890"},
    "eleventhPrice":{"amount":"4,000","ticket_number":"1234567890"},
    "category": "Normal"
}

###
PUT http://localhost:3001/v1/update-result HTTP/1.1
Content-Type: application/json

{
    "id":"63f9ed1dc14fa8aef92740af",
    "firstPrice" : {"ticket_number":"123"},
    "secondPrice": {"ticket_number":"1234567890"},
    "thirdPrice":{"ticket_number":"1234567890"},
    "fouthPrice":{"ticket_number":"1234567890"},
    "fifthPrice":{"ticket_number":"1234567890"},
    "sixthPrice":{"ticket_number":"1234567890"},
    "eightPrice":{"ticket_number":"1234567890"},
    "ninthPrice":{"ticket_number":"1234567890"},
    "tengthPrice":{"ticket_number":"1234567890"},
    "eleventhPrice":{"ticket_number":"1234567890"},
    "category":"Normal"
}